name: branch

on:
  push:
    branches-ignore: [gh-pages, main]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: setup project
      run: flutter create .
    - name: fix
      run: rm test/widget_test.dart
    - name: analyze
      run: flutter analyze
    - name: test
      run: |
        flutter test --coverage
        lcov -l coverage/lcov.info
        genhtml coverage/lcov.info -o coverage/html
    - name: build web
      run: flutter build web
