# .github/workflows/branch.yml
name: branch

on:
  push:
    branches-ignore: [gh-pages, main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: wtnb75/actions/flutter@v1
    - uses: wtnb75/actions/fluttertest@v1
    - name: cleanup default icons
      run: rm -f web/icons/Icon*.png
      shell: bash
    - uses: wtnb75/actions/flutterbuild@v1
      with:
        base-href: "/${{ github.event.repository.name }}/"
