name: main

on:
  push:
    branches: [main, test-deploy]
  workflow_dispatch: {}


jobs:
  build:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: prepare
      run: sudo apt-get install -y lcov
    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter
    - name: setup flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: setup project
      run: flutter create .
    - name: fix
      run: |
        rm -f web/icons/Icon*.png
    - name: analyze
      run: flutter analyze
    - name: test
      run: |
        flutter test --coverage
        (
          echo "# Coverage report"
          echo ""
          echo '```'
          lcov -l coverage/lcov.info
          echo '```'
        ) >> $GITHUB_STEP_SUMMARY
        genhtml coverage/lcov.info -o coverage/html
    - name: build web
      run: flutter build web --wasm --base-href "/${{ github.event.repository.name }}/" --no-tree-shake-icons
    - name: disable jekyll
      run: touch build/web/.nojekyll
    - name: copy coverage output
      run: cp -r coverage/html/ build/web/coverage/
    - name: setup pages
      uses: actions/configure-pages@v5
    - name: upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/web
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: deploy to gh-pages
      uses: actions/deploy-pages@v4
      id: deployment
