# .github/workflows/main.yml
name: main

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: wtnb75/actions/flutter@v1
    - uses: wtnb75/actions/fluttertest@v1
    - name: cleanup default icons
      run: rm -f web/icons/Icon*.png
      shell: bash
    - uses: wtnb75/actions/flutterbuild@v1
      with:
        base-href: "/${{ github.event.repository.name }}/"
    - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
    - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      with:
        path: build/web

  deploy:
    needs: build
    if: github.ref_name == 'main'
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: deploy pages
      id: deployment
      uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
